version: '3'

services:
  webserver:
    image: phpmyadmin/phpmyadmin
    deploy:
      replicas: 3
    ports:
      - "88:80"
    environment:
      PMA_HOST: dbserver
    networks:
      webnet:

  dbserver:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      webnet:

networks:
  webnet:
