version: '3'

services:
  apache2:
    image: git.netcologne.de:4567/oeberlein/apache2whnc
    
    #restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/webcluster01/htdocs:/htdocs
      - /srv/webcluster01/dehydrated/certs:/srv/dehydrated/certs
      - /srv/webcluster01/apache2_virtual-server-80-443:/etc/apache2/virtual-server-80-443
      - /srv/webcluster01/apache2_redirect-server:/etc/apache2/redirect-server
    extra_hosts:
      - "webdb01:10.20.30.12"
      - "webdb01.netcologne.de:10.20.30.12"
      - "webdb.local:10.20.30.12"
    networks:
      isolated:

networks:
  isolated:



