version: '3.7'

services:
  apache-Service:
    image: httpd:2.4
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
    networks:
      - haproxynet

  haproxy:
    image: haproxytech/haproxy-debian:2.0
    deploy:
      replicas: 1
    volumes:
      - ./etc:/etc/haproxy
    networks:
      - haproxynet
    ports:
      - target: 80
        published: 8888
        protocol: tcp
        mode: host
      - target: 443
        published: 9443
        protocol: tcp
        mode: host
    dns:
      - 127.0.0.11

networks:
  haproxynet:
    driver: overlay
