version: '3'

services:
  webserver:
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"     # The HTTP port
    environment:
      PMA_HOST: dbserver

    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock # So that Traefik 
    networks:
      webnet:

  dbserver:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      webnet:

networks:
  webnet:
