#!/bin/sh

#PHPRC="/htdocs/fcgi5/f/133b2d1a2dac5fb3a00c4fa95d6d5b35"
#export PHPRC
#PHP_INI_SCAN_DIR="/htdocs/fcgi5/f/133b2d1a2dac5fb3a00c4fa95d6d5b35/conf.d"
#export PHP_INI_SCAN_DIR
exec /usr/local/php7.3/bin/php-cgi