version: '3'

services:
  apache2debian:
    image: apache2debian:latest
    #restart: always
    ports:
      - 8888:80
    networks:
      isolated:
    volumes:
      - ./varwww:/var/www/html

  php:
      image: php:7.3-fpm-stretch
      #restart: always
      ports:
          - 9000:9000
      volumes:
        - ./varwww:/var/www/html
      deploy:
        resources:
          limits:
            cpus: '0.10'
            memory: 50M
          reservations:
            cpus: '0.10'
            memory: 20M
      networks:
        isolated:

networks:
  isolated:



